TOKEN_TELEGRAM = '5001454581:AAGXNd0w_kwgXGZsvHozjs8ROh8Ijjlchqc'
CHAT_ID_TELEGRAM = "402059449"
DAX_MT5 = "GER.30"
NASDAQ_MT5 = "NAS100"
SP500_MT5 = "SPX500"
DOW_MR5 = "USA.30"
ETH_MT5 = "ETHUSD"
BTC_MT5 = "BTCUSD"
FRA_MT5 = "FRA.40"
ESP_MT5 = "ESP.35"
JPN_MT5 = "JPN225"
AUS_MT5 = "AUS200"
ALIBABA_MT5 = "#BABA"
BAC_MT5 = "#BAC"
BIDU_MT5 = "#BIDU"
FB_MT5 = "#FB"
TESLA_MT5 = "#TSLA"
AMAZON_MT5 = "#AMZN"
GOOGLE_MT5 = "#GOOGL"
APPLE_MT5 = "#AAPL"
NETFLIX_MT5 = "#NFLX"
TWITTER_MT5 = "#TWTR"
symbols = {
    "AUDCAD": 0,
    "AUDCHF": 0,
    "AUDJPY": 0,
    "AUDNZD": 0,
    "AUDUSD": 0,
    "BTCUSD": 0,
    "CADJPY": 0,
    "GER.30": 0,
    "EURAUD": 0,
    "EURCAD": 0,
    "EURGBP": 0,
    "EURJPY": 0,
    "EURNZD": 0,
    "EURUSD": 0,
    "GBPAUD": 0,
    "GBPCAD": 0,
    "GBPJPY": 0,
    "GBPNZD": 0,
    "GBPUSD": 0,
    "US500": 0,
    "US100": 0,
    "NZDCAD": 0,
    "NZDJPY": 0,
    "NZDUSD": 0,
    "USDCAD": 0,
    "USDJPY": 0,
    "XAUUSD": 0
}
AUDCAD = "AUDCAD"
AUDCHF = "AUDCHF"
AUDJPY = "AUDJPY"
AUDNZD = "AUDNZD"
AUDUSD = "AUDUSD"
BTCUSD = "BTCUSD"
CADJPY = "CADJPY"
CADCHF = "CADCHF"
CHFJPY = "CHFJPY"
DAX = "GER.30"
EURAUD = "EURAUD"
EURCAD = "EURCAD"
EURCHF = "EURCHF"
EURGBP = "EURGBP"
EURJPY = "EURJPY"
EURNZD = "EURNZD"
EURUSD = "EURUSD"
GBPAUD = "GBPAUD"
GBPCAD = "GBPCAD"
GBPCHF = "GBPCHF"
GBPJPY = "GBPJPY"
GBPNZD = "GBPNZD"
GBPUSD = "GBPUSD"
SP500 = "US500"
NASDAQ = "US100"
NZDCAD = "NZDCAD"
NZDCHF = "NZDCHF"
NZDJPY = "NZDJPY"
NZDUSD = "NZDUSD"
USDCAD = "USDCAD"
USDCHF = "USDCHF"
USDJPY = "USDJPY"
USDZAR = "USDZAR"
XAUUSD = "XAUUSD"
LONG_STRATEGY = "follow"
SHORT_STRATEGY = "manual"
SCALPING_STRATEGY = "scalp"
eventFound = False